### ISSUE TITLE
Support ClientConfig

### ISSUE THREAD

**Issue by raananraz** [noctarius/snowcast#9]
Currently buildSnowcastAwareConfig only supports config.
Can you set it to support clientconfig?

**Comment by noctarius** [comment]
You don't need to since it configures the services configuration for snowcast, this is not necessary for clients :)

**Comment by raananraz** [comment]
so in client mode i don't need to set any configuration? (not even on the server hazelcast.xml?)

**Comment by noctarius** [comment]
You have to configure the server side but no configuration needed on client side. Server side needs to know about the snowcast service to handle client requests.
Will add a separate section to the documentation for this later today :)

**Comment by raananraz** [comment]
got it thanks!
nothing is required on the server besides the xml right? (any jars?)

**Comment by noctarius** [comment]
Exactly you got it, just the service registration using Config API, XML and the JAR obviously :)

I'm not going to close it yet since I first want to add the docs :)

**Comment by raananraz** [comment]
thx for the prompt reply!

so i do need the jar deployed on the server as well? 
anyway to overcome this?

(not sure i understand the usage here..)

**Comment by noctarius** [comment]
Sorry for the late answer but yes you have to deploy it on the server-side since the snowcast service, the system that manages the logical node ids and client requests, needs to be available. Otherwise the Hazelcast node doesn't know what it has to do or how to handle requests.

Added a new configuration part for this: https://github.com/noctarius/snowcast#hazelcast-client-configuration

**Comment by raananraz** [comment]
thanks a lot! ;)
